name: Trigger Checks on Fork
on: [issue_comment]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: listen for PR Comments
        uses: machine-learning-apps/actions-chatops@master
        with:
          APP_PEM: ${{ secrets.APP_PEM }}
          APP_ID: ${{ secrets.APP_ID }}
          TRIGGER_PHRASE: "/check-pr"
        env: # you must supply GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.manual_github_token }}
        id: prcomm
        # This step clones the branch of the PR associated with the triggering phrase, but only if it is triggered.
      - name: clone branch of PR
        if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
        uses: actions/checkout@master
        with:
          ref: ${{ steps.prcomm.outputs.SHA }}

        # This step is a toy example that illustrates how you can use outputs from the pr-command action
      - name: print variables
        if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
        run: echo "${USERNAME} made a triggering comment on PR# ${PR_NUMBER} for ${BRANCH_NAME}"
        env: 
          BRANCH_NAME: ${{ steps.prcomm.outputs.BRANCH_NAME }}
          PR_NUMBER: ${{ steps.prcomm.outputs.PULL_REQUEST_NUMBER }}
          USERNAME: ${{ steps.prcomm.outputs.COMMENTER_USERNAME }}
      
      - name: Check Spelling
        uses: UnicornGlobal/spellcheck-github-actions@master
        
      - name: Link Checker
        id: lc
        uses: peter-evans/link-checker@v1
        with:
          args: -v -r *
      - name: Fail if there were link errors
        run: exit ${{ steps.lc.outputs.exit_code }}
        
      - name: Comment on PR if checks pass
        if: success()
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.manual_github_token}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 All checks passed!'
            })
        
      - name: Comment on PR if checks fail
        if: failure()
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.manual_github_token}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Some checks failled :(, check Github Actions for more details.'
            })
