name: Check markdown links
on:
  schedule:
  - cron: '0 0 1 * *'
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        uses: peter-evans/link-checker@v1.2.2
        with:
          args: -v -r *
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Link Checker Report
          content-filepath: ./link-checker/out.md
          labels: report, automated issue
